textpattern/textpattern

textpattern/include/txp_discuss.php
textpattern/include/txp_log.php

I chose IANA on the basis they're not tied to a particular registrar and seemed to be as neutral or independent as they come.

Make IP addresses into whois links

---

README.txt

A handful of lines hit 80 characters, but this is 2015 so we'll probably be OK.

README tweaks (security, clarity and branding)

---

README.txt

README tweaks

---

README.txt

@Bloke & @philwareham - if I'm making non-code changes to `master` (like this), should I also update `admin-layout-update`, too?

Add system requirements check to upgrade pre-flight

---

CONTRIBUTING.textile

This should really be a `.txt` file instead of a `.textile`.
Either that, or the `README` should be Textile'd, too.

Tidy up `CONTRIBUTING.textile`

---

README.textile

See https://github.com/textpattern/textpattern/issues/475

First attempt at `README.textile`

---

README.textile

Getting there. My word fu isn't strong today.

More `README.textile` bizniz

---

textpattern/setup/index.php

Min'd version is about 30% smaller.

Have setup use minified CSS.

---

textpattern/include/txp_article.php
textpattern/lib/txplib_wrapper.php
textpattern/setup/en-gb.php
textpattern/setup/txpsql.php
textpattern/update/_to_4.6.0.php

Background: http://forum.textpattern.com/viewtopic.php?id=45860
Supersedes: https://github.com/textpattern/textpattern/pull/489
Now in a single commit, for a mintier taste.

Remove textpattern.com ping functionality - take two

---

textpattern/setup/txpsql.php

Supersedes https://github.com/textpattern/textpattern/pull/491

Remove textgarden.org link and About section from new installs

---

HISTORY.txt

I do this to save @philwareham a trivial task.

Add item about About section's demise

---

textpattern/lib/constants.php
textpattern/lib/txplib_misc.php

Introduce do_list_unique()

---

HISTORY.txt
textpattern/index.php
textpattern/lib/constants.php
textpattern/lib/txplib_html.php
textpattern/lib/txplib_misc.php
textpattern/lib/txplib_publish.php
textpattern/publish.php

Issue #497 
Slightly rewritten code.

Introduce Admin Side trace log

---

textpattern/publish.php

Move RAW PHP to function output_file_download()

---

textpattern/publish/taghandlers.php

Discussion: http://forum.textpattern.com/viewtopic.php?id=46062

Remove unnecessary warning in if_expired tag

---

textpattern/lib/txplib_db.php
textpattern/lib/txplib_misc.php
textpattern/publish.php
textpattern/publish/atom.php
textpattern/publish/rss.php
textpattern/publish/taghandlers.php

Applying `do_list_unique()`, Issue #196 
The test cases for testing `before`/`after`
* `<txp:article_custom section="ss,ss,ss,ss,ss" category="cc,cc,cc,c2,c2" author="aa,aa,aa,aa" id="1,2,3,4,3,3,3" keywords="kk,kk,kk,kk" />`
> [SQL (0.000356): select *, unix_timestamp(Posted) as uPosted, unix_timestamp(Expires) as uExpires, unix_timestamp(LastMod) as uLastMod from test1com_textpattern as textpattern where 1=1 and Status >= 4 and Posted <= now() and (now() <= Expires or Expires = '0000-00-00 00:00:00') and ID IN (1,2,3,4,3,3,3) and (Category1 IN ('cc','cc','cc','c2','c2') or Category2 IN ('cc','cc','cc','c2','c2')) and Section IN ('ss','ss','ss','ss','ss') and AuthorID IN ('aa','aa','aa','aa') and (FIND_IN_SET('kk',Keywords) or FIND_IN_SET('kk',Keywords) or FIND_IN_SET('kk',Keywords) or …

More correct SQL queries

---

textpattern/lib/txplib_misc.php

This applies the parts of the patch in issue #261 that result in reduced memory usage. The remainder of the patch in that issue was rejected, so applying this one would close that issue.
It also removes the unneeded "empty" call.

Fix issue #261: Reduce load_lang memory usage. 

---

textpattern/lib/IXRClass.php
textpattern/lib/PasswordHash.php

Use PHP5 constructors (instead of PHP4)

---

textpattern/include/txp_diag.php

Minor change on diagnostics panel. Hides the warning about a 'newer' version being available and the warnings about modified files. Both don't make sense if you're running the development version.

Diag: hide update version and file modification warnings when using SVN

---

textpattern/include/txp_discuss.php
textpattern/publish/comment.php
textpattern/publish/taghandlers.php
textpattern/setup/txpsql.php
textpattern/update/_to_4.6.0.php

This would fix #17
Non-empty txp_discuss_ipban tables are preserved, while empty ones are removed.

Remove comments IP ban functionality

---

textpattern/update/_to_4.6.0.php

Set theme to Hive when upgrading (fix #607)

---

textpattern/include/txp_list.php

Fix regression when no Expires date is set

---

sites/README.txt

Edits to README.txt as requested, chunked into different commits for the different new infos/revisions.
Technically an additional note should be made to the readme in txp's base directory about not installing a multi-site installation in a web-readable directory, but I fear that will only cause confusion. Ideas?

Multi site fix

---

index.php
textpattern/publish.php

Fixes regressions caused by #549

Avoid errors when publish.php is included by a plugin

---

sites/site1/public/index.php

- Reflects change to trace routines for debugging added in ruud's pull update #549
- Maintains path differences for multi-site installation

Update multisite index.php to match base index.php

---

textpattern/lib/txplib_misc.php
textpattern/lib/txplib_publish.php

Reverts textpattern/textpattern#651

Revert "Master sync"

---

textpattern/setup/article.body.textile

Scrub 'fails' -- this stuff is actually stable, after all.

Less fatalist language in default article

---

textpattern/textpattern.js

This patch should make the prefs panes expandable by the hash portion of the URL.

Make prefs panes URL-selectable

---

HISTORY.txt

Formatting and arrangement, plus change relating to Atom feeds in https://github.com/textpattern/textpattern/pull/734

Tidying HISTORY.TXT

---

HISTORY.txt

Addresses: https://github.com/textpattern/textpattern-default-theme/issues/72

Bump IE version requirements

---

textpattern/publish/atom.php
textpattern/publish/rss.php

Removing forced compression RSS and Atom feeds.

---

sites/site1/public/theme

was `theme`, should be `admin-themes`

Fix multisite theme symlink

---

README.txt

OS X will become macOS soon, plus uniformity tweaks.

`README.txt` tweaks

---

README.txt

Important stuff goes further up, switch docs reference to .io, plus tweaks.
Addresses https://github.com/textpattern/textpattern/issues/755

Reorder `README.txt` plus tweaks

---

textpattern/setup/article.body.textile

See https://github.com/textpattern/textpattern/issues/755 for info.

Switch another docs ref away from wiki to .io

---

README.txt

See https://github.com/textpattern/textpattern/commit/1d2d37f1aa37e089c23e44e14916864d1d809cba for info

Repoint licence locations

---

textpattern/textpattern.js

Save pane states on keyboard focus too

---

textpattern/setup/txpsql.php

Fix Issue: #775 
This patch should be applied to `dev` branch, too.

Bugfix: No preferences sql_now_*

---

textpattern/lib/txplib_db.php

* Record the number of rows returned by the SQL query.
* Remove unused `global $txpcfg`

A more complete SQL tracing

---

textpattern/update/_update.php

Put it in a branch atm to test later.

Update dbversion on every release

---

textpattern/include/txp_admin.php
textpattern/include/txp_article.php
textpattern/include/txp_auth.php
textpattern/include/txp_category.php
textpattern/include/txp_lang.php
textpattern/include/txp_link.php
textpattern/include/txp_plugin.php
textpattern/include/txp_section.php

Issue #802 
Please do not apply this patch is, I want to check out the other form.

Required attribute for input fields

---

css.php
textpattern/index.php
textpattern/lib/txplib_misc.php
textpattern/publish.php
textpattern/setup/index.php

Make all HTTP headers use Train-Case

---

textpattern/publish/taghandlers.php

Returns true or false, output as '1' or '' when parsed.

Single form of <txp:if_tags />

---

textpattern/publish/atom.php
textpattern/publish/rss.php

Small optimization and code simplification.
* Minus one sql query (prefs `lastmod` already loaded)
* Minor code sync between atom.php and rss.php

Simplification atom/rss feed

---

textpattern/include/txp_discuss.php
textpattern/include/txp_list.php

Search comments per parent in one click

---

textpattern/publish/atom.php
textpattern/publish/rss.php

Fix warning
`http://domain.com/?rss=1&area=link`
```
Tag error:  -> Notice: Undefined variable: uLastMod while parsing form <strong>None</strong> on page <strong>default</strong>
```
and formatting feeds output

Fix feed warning + formatting output

---

textpattern/lib/txplib_publish.php

This fixes an issue reported in https://forum.textpattern.io/viewtopic.php?id=47793

Avoid undefined variable notices

---

textpattern/vendors/Textpattern/DB/Core.php

Excluding custom.prefs from auto checking preferences

---

textpattern/lib/txplib_misc.php

Clear the output buffer before running the test.
https://forum.textpattern.io/viewtopic.php?id=47898

Stable test of clean URLs

---

textpattern/include/txp_tag.php
textpattern/lib/txplib_head.php

* Cleaned the code repetition.
* Use pagetop() to set the CSP headers in `async` mode

Set CSP headers from one location

---

HISTORY.txt

Cosmetic changes to `HISTORY.txt`

---

textpattern/setup/index.php

Fix JS warning:
```
jQuery.Deferred exception: this.dialog is not a function jQuery.fn.txpDialog
TypeError: this.dialog is not a function
```

Include jquery-ui.js in the Setup

---

textpattern/include/txp_article.php
textpattern/include/txp_auth.php
textpattern/include/txp_diag.php
textpattern/lib/constants.php
textpattern/lib/txplib_head.php
textpattern/lib/txplib_html.php
textpattern/lib/txplib_misc.php
textpattern/publish/taghandlers.php
textpattern/setup/index.php

The readable output of json_encode()

---

textpattern/include/txp_diag.php

Issue #839 
TODO: Need change textpack string `problem_connecting_rpc_server`

Use JSON file to check for new releases

---

textpattern/include/txp_diag.php

Show `last_update_check` in detailed diagnostics

---

textpattern/include/txp_diag.php

Issue #839 
@philwareham , check, please.

Check prerelease updates.

---

textpattern/include/txp_css.php
textpattern/include/txp_form.php
textpattern/include/txp_page.php

See https://forum.textpattern.io/viewtopic.php?id=48126.

Adds a dedicated hook per action

---

textpattern/vendors/Textpattern/Skin/Main.php

The error status was not the right one on multi-edit depending of the order of the skin throwing the error.

Fixes error status

---

textpattern/vendors/Textpattern/Skin/Skin.php

Uses 4 spaces for indentations.

Themes branch: JSON pretty print for PHP 5.3.x

---

textpattern/vendors/Textpattern/Skin/AssetBase.php
textpattern/vendors/Textpattern/Skin/Main.php
textpattern/vendors/Textpattern/Skin/RecDirIterator.php
textpattern/vendors/Textpattern/Skin/Skin.php
textpattern/vendors/Textpattern/Skin/SkinBase.php

See https://github.com/textpattern/textpattern/commit/f69507842e77443e8ed9f8dddd30eef56a9eb7b0#commitcomment-25136618.

Themes branch: Get variable definitions out of condition clauses

---

textpattern/lib/txplib_db.php
textpattern/lib/txplib_misc.php
textpattern/publish.php

- {Please write here}
- {Please write here}
- {Please write here}

Bloatware patch 1

---

HISTORY.txt

Minor language tweak in `HISTORY.txt`, more appropriate and fewer negative connotations.

`Old` -> `legacy`

---

HISTORY.txt

https://github.com/textpattern/textpattern/commit/daa6aba212b4ad4d6b2d8c7a24d9c4a175d6278c

`zxcvbn` is no more

---

textpattern/lib/txplib_publish.php

Comment update, no code changes.
Tags this TODO with issue https://github.com/textpattern/textpattern/issues/1009

Update TODO comment to point to issue

---

rpc/TXP_RPCServer.php

https://github.com/textpattern/textpattern/issues/1052

Update comment connecting to an issue, no code changes

---

rpc/index.php

https://github.com/textpattern/textpattern/issues/1012

Update comment to link to issue, no code changes

---

textpattern/include/txp_skin.php
textpattern/vendors/Textpattern/Skin/AssetBase.php
textpattern/vendors/Textpattern/Skin/Forms.php
textpattern/vendors/Textpattern/Skin/Main.php
textpattern/vendors/Textpattern/Skin/SharedBase.php

- notices related error fixed (thanks @phiw13);
- extra form files cleaning fixed.
- remove_extra_templates related checboxes moved before the label (as asked by @Bloke [here](https://github.com/textpattern/textpattern/issues/1035#issuecomment-347835023); still needs the hidden pref to work as suggested);

Skin package patches

---

textpattern/vendors/Textpattern/Skin/Main.php

See commit.
Thanks @philwareham for merging my patches!

Skin package patch

---

HISTORY.txt

Small `HISTORY.txt` tweaks

---

.github/txp-checksums.php

2018 year bump

---

textpattern/setup/index.php

See https://github.com/textpattern/textpattern/issues/1100 and https://github.com/textpattern/textpattern/issues/1100#issuecomment-356615845

Comment out `setup_autoinstall_text` reference

---

textpattern/include/txp_lang.php

Changes the notification dialog from 'language updated' to 'language installed'.
See https://github.com/textpattern/textpattern/issues/1104

Dialog tweak when language is installed

---

themes/.htaccess

See https://github.com/textpattern/textpattern/issues/1107#issuecomment-356905937

Fix themes `.htaccess`

---

HISTORY.txt

https://om.co/2018/01/18/dean-allen-rest-in-peace/

Cheers, Dean

---

HISTORY.txt

/cc https://github.com/textpattern/textpattern/commit/5e6fc44d6eb10c912b3d630bec93efa812045bd0 https://github.com/textpattern/textpattern/commit/9868bb9a914007c9d21996d9e6218f1a48c042d3

Tweak history, add two tag changes

---

HISTORY.txt

Mostly formatting, add credit for multi-site to @jools-r

More history refactoring

---

textpattern/vendors/Textpattern/Skin/AssetBase.php

Missing commit to update `last_template_saved` on skin switching

---

textpattern/vendors/Textpattern/Skin/AssetBase.php
textpattern/vendors/Textpattern/Skin/Skin.php

You can merge or wait for the next commits about https://github.com/textpattern/textpattern/issues/1154.

Textpack strings corrections (fixes textpattern/textpattern/issues/1137)

---

textpattern/lib/txplib_misc.php
textpattern/setup/setup_lib.php
textpattern/vendors/Textpattern/Skin/AssetBase.php
textpattern/vendors/Textpattern/Skin/CommonBase.php
textpattern/vendors/Textpattern/Skin/Skin.php

- Moves `isDirEmpty()` to txplib_misc.php as `is_dir_empty()`;
- Do not accept unknown public theme name: related to https://github.com/textpattern/textpattern/issues/1160 + https://github.com/textpattern/textpattern/issues/1158.

Skin enhancements

---

textpattern/vendors/Textpattern/Skin/Skin.php

Important: fixes regression about skin related sections update

---

textpattern/vendors/Textpattern/Skin/AssetBase.php

Related to https://github.com/textpattern/textpacks/issues/261.

Skin related textpack strings updates

---

textpattern/setup/index.php
textpattern/setup/setup_lib.php
textpattern/vendors/Textpattern/Skin/AssetBase.php
textpattern/vendors/Textpattern/Skin/Skin.php
textpattern/vendors/Textpattern/Skin/SkinInterface.php

Skin related improvements

---

textpattern/setup/data/txp_category.xml

RIP, Dean Cameron Allen.
https://textpattern.io/img/article-832w/53.jpg
I've been thinking about how we can mark Dean's passing and legacy with more than a single-line entry in `HISTORY.txt`. This is my proposal.

Add "Everything is going to be alright" article category

---

textpattern/vendors/Textpattern/Skin/Skin.php

See https://github.com/textpattern/textpattern/pull/1168#pullrequestreview-99995415.

Skin patch

---

textpattern/setup/.default-dist.json

See https://github.com/textpattern/textpattern/issues/1174

Encourage CLI installer folks to populate the URL

---

HISTORY.txt

Punctuation and attribution format (username not first name) changes, nothing more.

Minor uniformity tweaks to `HISTORY.txt`

---

textpattern/vendors/Textpattern/Skin/Skin.php

See https://github.com/textpattern/textpattern/issues/1194.

Fixes incorrect HTML structure / markup on the Themes panel

---

.github/ISSUE_TEMPLATE.md

- add Textpattern version number requirement

Tweak `ISSUE_TEMPLATE.md`

---

HISTORY.txt

- alphabetical reordering
- hat tips
- other tweaks

Tweaks to `HISTORY.txt`

---

README.txt

- tweak `README` to include old version stuff
partially addresses https://github.com/textpattern/textpattern/issues/1257

Clarify pre-4.2.0 update situation

---

README.md

- Remove -dev version number for now

Remove -dev version number for now

---

textpattern/vendors/Textpattern/Skin/AssetBase.php
textpattern/vendors/Textpattern/Skin/AssetInterface.php
textpattern/vendors/Textpattern/Skin/CommonBase.php
textpattern/vendors/Textpattern/Skin/CommonInterface.php
textpattern/vendors/Textpattern/Skin/Css.php
textpattern/vendors/Textpattern/Skin/CssInterface.php
textpattern/vendors/Textpattern/Skin/Form.php
textpattern/vendors/Textpattern/Skin/FormInterface.php
textpattern/vendors/Textpattern/Skin/Page.php
textpattern/vendors/Textpattern/Skin/PageInterface.php
textpattern/vendors/Textpattern/Skin/Skin.php
textpattern/vendors/Textpattern/Skin/SkinInterface.php

```
namespace Textpattern\Skin {
…
}
```
to 
```
namespace Textpattern\Skin;
…
```

Skin related braces-free namespaces

---

textpattern/vendors/Textpattern/Skin/Skin.php

- removes a useless variable setting.

Removes useless variable

---

README.md

- Updated/fixed the links to the 4.7.1 archives

Update download links in README.md

---

textpattern/include/txp_css.php
textpattern/include/txp_form.php
textpattern/include/txp_page.php
textpattern/publish/taghandlers.php

Fixes #1387

---

.github/ISSUE_TEMPLATE/Bug_report.md

Changes proposed in this pull request:  add web server, database and PHP specifics without being too onerous.

Add more info to bug report template

---

textpattern/lib/txplib_html.php
textpattern/lib/txplib_publish.php

- {Please write here}
- {Please write here}
- {Please write here}

482 recovery bloke

---

README.md

Tweaks to ensure compliance with @digitalocean open source sponsorship guide.

Add DigitalOcean logo to README

---

textpattern/publish/taghandlers.php

- Addition of escape="url_title" using built-in stripSpace function
Addresses Issue #1803

Add escape="url_title" option

---

rpc/TXP_RPCServer.php

Allows for image upload over the MovableType API, thanks to @Bloke @redsweater @jakob for the help!

Implemented metaWeblog.newMediaObject

---

rpc/TXP_RPCServer.php
textpattern/lib/IXRClass.php
textpattern/lib/txplib_wrapper.php
textpattern/setup/themes/four-point-nine/pages/default.txp

- Fixes for RPC under PHP 8+
- More robust image upload support via RPC
- Fixes to Body_HTML data not being populated by RPC edits
- Proper support for post status in RPC clients
- Fixes to timezone error in RPC
- Fixes to error in the event a category is not set on a post in RPC
- Support for auto settings detection for RPC clients added to default template

RPC Improvements

---

textpattern/include/txp_article.php

Addition of two pluggable_ui callbacks for the write tab:
- pane_header
- save_zone

Add pluggable_ui callbacks for write tab
