- textpattern/lib/txplib_misc.php
- textpattern/publish.php
This patch allows you to trace memory usage and help you find a Form/Tag/Plugin/SQL query that takes a lot of memory.
Forum thread
http://forum.textpattern.com/viewtopic.php?pid=292775#p292775
> Debug log: trace MemUsage

- textpattern/include/txp_article.php
A quick fix to prevent expiry date inconsistencies and surprising messages/behaviours.
> article_validate() returns immediately if message not empty. See #245

- textpattern/lib/txplib_misc.php
The alert appeared after a failed login due to an missing parameter in a call to the mysqli_get_server_info function.
> Fix 'internal error' javascript alert

- textpattern/lib/txplib_misc.php
Discussion: http://forum.textpattern.com/viewtopic.php?id=46062
* For expired articles is returned link to `site_url/#expired_article`
* Show warning `permlink_to_expired_article` if `production_status != 'live'` && `txpinterface == 'public'`
> Avoid links to expired articles

- textpattern/include/txp_category.php
- textpattern/lib/txplib_misc.php
Fixes issue #250 and shows the invalid name in the error message if a category cannot be created (instead of not showing it at all). See commit messages and issue #250 for more detail.
> fix issue #250 and show correct error message.

- textpattern/include/txp_auth.php
Generate a HTTP 401 response if a user fails to log in or tries to log in with a bad cookie. Fixes issue #411
> Fix issue #411

- textpattern/publish.php
Fix minor bug after pull request https://github.com/textpattern/textpattern/pull/511
Reproduce bug:  `<txp:article_custom form="article_listing" />`
Error:
`Tag error: <txp:article_custom form="article_listing" /> ->  Notice: Undefined variable: listform while parsing form default on page archive`
> Fix undefined variable: listform

- textpattern/lib/txplib_misc.php
Sometimes, sites with a large number of forms can be difficult to find what form is called from.
This patch shows the nesting of forms in the trace log.
Sample output:
```
<txp:output_form form="subitem_list" />
[Form: 'subitem_list']
[Nesting forms: 'default' / 'article_listing' / 'subitem_list']
```
> Trace log: Nesting forms

- textpattern/include/txp_tag.php
- textpattern/lang/en-gb.txt
- textpattern/setup/en-gb.php
A lot of attributes were not available through the tagbuilder, so I only moved the ones that were already there so the tagbuilder at least doesn't create tags with deprecated attributes (due to fixed issue #29).
Is the tagbuilder scheduled for removal or is there still commitment to keep it in TXP?
> update tagbuilder after changes in comments_form tags

- textpattern/publish/taghandlers.php
Using fetch_form allows the form to be cached.
> use fetch_form() in the search_input taghandler

- textpattern/publish/taghandlers.php
search_input has a lot of attributes, but apart from 'form', none of them have any effect, unless you also set form to either an empty string or a non-existent form. That is too much magic for a user. This patch checks if there are any other attributes specified (besides form). If so, it assumes that you don't want to use the form.
This is one of the possible ways to fix issue #541
> Make search_input behave more as expected.

- rpc/index.php
- textpattern/include/txp_admin.php
- textpattern/include/txp_discuss.php
- textpattern/include/txp_file.php
- textpattern/include/txp_form.php
- textpattern/include/txp_image.php
- textpattern/include/txp_link.php
- textpattern/include/txp_list.php
- textpattern/include/txp_log.php
- textpattern/include/txp_plugin.php
- textpattern/include/txp_section.php
- textpattern/index.php
- textpattern/lib/txplib_head.php
- textpattern/lib/txplib_misc.php
This series of commits reduces the amount of SQL queries on the admin side:
* remove unused privs query in pagetop function (saves 1 query)
* remove unnecessary query to fetch $dbversion (saves 1 query)
* don't fetch global prefs twice (saves 1 query). Does involve a change in the get_prefs function.
* don't store private user sorting prefs if the user didn't change them (saves 4 queries)
* don't count users twice on user list page (saves 1 query typically)
* cache has_single_author results (saves 1 or 2 queries)
* use joins on the links and images pages to avoid separate queries for each category / author name (saves up to 2 queries per link / image)
On most admin-side pages this results in 8 less SQL queries.
And a few optimisations:
* use 'show tables' instead of 'describe table' to …
> Admin-side SQL query reduction / optimisation

- textpattern/lib/txplib_misc.php
Fix for a small bug in `getMetaDescription()` (issue #550). `$thissection` is an array not a string.
> Fixed bug setting $theSection in getMetaDescription() method.

- textpattern/vendors/Textpattern/Loader.php
Completes work done in #556 by removing the ability to use underscores for namespacing.
> Remove support for underscore pseudo-namespacing

- textpattern/include/txp_admin.php
- textpattern/include/txp_discuss.php
- textpattern/include/txp_file.php
- textpattern/include/txp_image.php
- textpattern/include/txp_link.php
- textpattern/include/txp_list.php
- textpattern/include/txp_log.php
- textpattern/include/txp_plugin.php
- textpattern/include/txp_section.php
- textpattern/publish/atom.php
I could fix it either by lowercasing $dir or by making an exception to the rule of having uppercase SQL keywords. The latter was preferable here because the change in case also affected the contents of a pref, causing a potential reversal of stored sort direction on upgrades.
> Fix regression caused by #570 (SQL coding style fixes)

- textpattern/publish/taghandlers.php
This affects the following tags: 
* popup_comments
* comments_form
* comments
* comments_preview
If this pull request is accepted, an issue should be opened on the documentation repository to document this change and the fact that we have a popup_comments tag (not documented yet).
> Add container ability to comment tags that have form attribute

- textpattern/lib/constants.php
- textpattern/setup/txpsql.php
- textpattern/update/_to_1.0.0.php
- textpattern/update/_to_4.0.5.php
- textpattern/update/_to_4.0.7.php
- textpattern/update/_to_4.6.0.php
MySQL 5.7 by default no longer allows 0000-00-00 dates, which were used as the default on several columns in TXP tables.
This patch removes those defaults for NOT NULL columns and sets the default to NULL for NULL columns (textpattern:Expires and txp_users:last_access)
Zero dates in existing rows are converted to sensible values that are allowed.
This fixes issue #591 
Categories, when created or edited can be 64 chars long. A few other tables that used these categories allowed for longer names. That doesn't make sense, because they can't be longer than 64 chars, so I've changed those colums to varchar(64).
txp_token was added to the update scripts, but without NOT NULL and it was also missing from txpsql.php. Added it there and recreated the table to be more in line with the other …
> No zero dates in SQL. Category name 64 chars. Re-create txp_token

- .gitignore
- textpattern/include/txp_admin.php
- textpattern/include/txp_article.php
- textpattern/lib/constants.php
- textpattern/lib/txplib_publish.php
- textpattern/publish.php
- textpattern/publish/atom.php
- textpattern/publish/rss.php
- textpattern/publish/taghandlers.php
- textpattern/setup/txpsql.php
- textpattern/update/_to_4.6.0.php
Fix a few regressions caused by my earlier patch which removed zero dates.
This now does affect plugins that use the Expired column in the textpattern table. I removed the NULLDATETIME constant, because if you change it from NULL to something else, you also have to modify a lot of queries. No point in having it as a constant anymore.
PS. Please add "*~" to .gitignore (to exclude backup files created by unix text editors.)
> Fix NULL regressions

- textpattern/lib/txplib_publish.php
- textpattern/vendors/Textpattern/Tag/Registry.php
* Let $registry->processTags() return false if the tag is not registered or not callable (and a string otherwise). This makes it possible to avoid checking twice if a tag is registered, which makes parsing slightly faster.
* Clarify why doing is_callable during tag registering isn't enough and why we only do a syntax check there. This had me puzzled for a while.
* During processing, if we encounter an unregistered tag and it does appear to be an actual tag, register that tag and then process it again. It's enough to get one "unregistered tag" warning for each tag (if a tag occurs more than once).
* Remove some ancient code that has long been deprecated. No point in deprecating if the code never gets removed.
> Parser optimization and removal of ancient code

- textpattern/publish.php
- textpattern/publish/comment.php
- textpattern/publish/taghandlers.php
Put all the cleanup of comment form field values into the getComment() function. The advantage being that we get the same type of cleanup everwhere we use these values.
Evaluate required fields during preview at a much earlier stage, allowing errors to be shown even if the errors are to be displayed before the comment form fields. Fixes issue #623.
Add language string: comment_duplicate, which is an error message indicating that the comment was rejected, because the message was a duplicate (already exists in database).
> Improve comment error handling

- textpattern/include/txp_article.php
- textpattern/include/txp_list.php
Fixes issue #614. Changes are:
Duplicate from article write tab:
* reset posted time if that option is checked.
* always set last modified time to NOW.
Duplicate from articles list tab:
* don't change Posted and Expires dates.
* reset comments_count to zero.
* set last modified time to NOW (fixes issue #618).
* set status to draft if the old status was live/sticky
One difference remains. On the write tab, the url_title is regenerated from the title when duplicating. On the articles list tab, this doesn't happen.
Side effect: for new articles, the last modified time is now always set to NOW(). Previously, for articles set in the future it was set to the posted date. However when editing such an article, it would be reset to NOW(), so that didn't make much sense.
> More consistent duplicate behaviour

- textpattern/include/txp_lang.php
C locale always exists, so this avoids an exception getting thrown. Not falling back to C locale would mean the previous locale would remain set, which is undesirable, because then there would be a weird mismatch between locale and language.
> Fallback to C locale if desired locale doesn't exist. Fixes issue #603

- textpattern/include/txp_article.php
- textpattern/lib/txplib_publish.php
When articles are sorted by some non-unique value (e.g. Section), `<txp:link_to_next/prev />` can produce unexpected results. Same problem admin-side for articles with identical `Posted` value (e.g. cloned). This should fix it in some way.
> Fix link to next/prev behaviour

- textpattern/include/txp_list.php
- textpattern/lib/txplib_db.php
- textpattern/lib/txplib_forms.php
- textpattern/lib/txplib_html.php
- textpattern/lib/txplib_misc.php
- textpattern/publish.php
If things go west, throw milestones and revert `function join_atts($atts, $flags = TEXTPATTERN_STRIP_EMPTY_STRING)` back to `function join_atts($atts, $flags = TEXTPATTERN_STRIP_EMPTY)` in `txplib_misc.php`
> Preserve attr="0" in html tags (newly) created with "tag" functions by default

- textpattern/setup/txpsql.php
Section descriptions were numbers (misleading/incorrect), now they’re blank.
> Fix section name descriptions

- textpattern/include/txp_article.php
Was pointing to `title`. Oops.
> Show correct pophelp for article image

- .htaccess
Also remove the `# SVG` comment for uniformity. The other block doesn't have a comment, and it's pretty clear that the two lines refer to SVG stuff.
Tab indentation switched to four spaces, per other indentations.
> Specify where Textpattern-provided entries live & tweaks

- rpc/TXP_RPCServer.php
- rpc/index.php
- textpattern/lib/txplib_wrapper.php
Site is offline, has been for >12 months. This commit rewrites `kusor.com` links to most recent Wayback Machine grab at time of commit.
Addresses https://github.com/textpattern/textpattern/issues/695
> Rewrite kusor.com refs to Wayback Machine

- textpattern/include/txp_list.php
Issue: #774 
A similar situation may occur with: `image`, `link`, `file`. Now there are not checked right to change the author.
Probably it is necessary add a check of the rights: `image.edit`, `link.edit`, `file.edit` ?
> Show option "Change author" only if the user has rights

- textpattern/include/txp_tag.php
Normalises MAGIC_QUOTES_GPC and removes NULL bytes for $_POST['linktext']
> txp_tag: normalises $_POST value

- textpattern/publish/atom.php
Tiny HTTP spec compliance fix.
> Fix Content-type=>Content-Type in Atom responses (Train-Case)

- textpattern/publish/atom.php
- textpattern/publish/rss.php
This was a problem with Apache 1.3 (since patched), but Apache 2+ and other web servers don't have a problem with this anymore.
> Uncomment and enable HTTP 226 responses

- textpattern/lib/txplib_db.php
- textpattern/lib/txplib_misc.php
Provide a hint to search engines that errors shouldn’t be index. Will clear once the error is resolved.
> Tell robots to not index error pages

- textpattern/lib/txplib_misc.php
This is dead code, as far as I can tell; but fixing it anyway. Not all clients follow redirects automatically.
Redirect pages generated by all major web servers include a body message for redirects.
Users see informational page instead of blank page when redirect fails because of caching, network issues, tweaked browsers, accessibility settings, misuse of curl, etc. etc.
> Redirects should have a linked body message

- textpattern/publish/taghandlers.php
Helps designers target feed links more easily with CSS, and help robots and software figure out what the link leads to without following it.
All other major CMS provide this at least in their default themes.
> Include feed type="" attr in feed_link

- textpattern/publish/atom.php
- textpattern/publish/rss.php
- textpattern/vendors/Textpattern/Http/Request.php
Apache isn’t the only server in town anymore, and there is no reason to use this method rather than the superglobal variable.
> Swap apache_request_headers() for $_SERVER

- textpattern/lib/txplib_misc.php
- textpattern/publish/atom.php
- textpattern/publish/rss.php
New implementation supports returning feed deltas (just the new entries)
if the A-IM plus either the If-Modified-Since or If-None-Match headers.
* Always send a Vary header for feeds so caches will be variant aware.
* Disable caching when Txp is not in production.
* Don't lie about last modification dates.
* Derive ETags from last modification timestamps.
Follow up from issue #811, obsoletes #826.
> Fix feed delta implementation.

- package.json
JSON value for prerelease (beta, etc) should be `null` if there is no beta, and version number if if there is one.
> Add JSON for release and prerelease versions

- textpattern/include/txp_file.php
Two mini patches
– clicking on date column head in the file panel currently switches to the image panel!?
– add support for sorting the file list by date (using created date)
> file panel – date sort in file list

- textpattern/lib/txplib_misc.php
`txp_die()` return blank screen, if not exist `error_{$code}` and  `error_default` pages.
> Fix txp_die() blank screen

- textpattern/.htaccess
- textpattern/include/txp_tag.php
- textpattern/lib/constants.php
- textpattern/lib/txplib_head.php
Issue #408
* Reduces the mix of headers (.htaccess/php).
* It is possible to set the header under the nginx and other web servers.
> Set Content-Security-Policy header from php

- textpattern/include/txp_article.php
Uniformity: gTxt strings refer to 'expire' (multiple mentions), not 'expiry' (zero mentions).
There's a request for addition in Textpacks (https://github.com/textpattern/textpacks/issues/217), but if we can change this out then the more appropriate gTxt (`invalid_expiredate`) can be added to be a better fit.
(Please and thank you.)
> Switch gTxt `invalid_expirydate` to `invalid_expiredate`

- textpattern/include/txp_skin.php
- textpattern/vendors/Textpattern/Skin/AssetBase.php
- textpattern/vendors/Textpattern/Skin/AssetInterface.php
- textpattern/vendors/Textpattern/Skin/Forms.php
- textpattern/vendors/Textpattern/Skin/Main.php
- textpattern/vendors/Textpattern/Skin/MainBase.php
- textpattern/vendors/Textpattern/Skin/MainInterface.php
- textpattern/vendors/Textpattern/Skin/Pages.php
- textpattern/vendors/Textpattern/Skin/RecDirIterator.php
- textpattern/vendors/Textpattern/Skin/RecFilterIterator.php
- textpattern/vendors/Textpattern/Skin/RecIteratorIterator.php
- textpattern/vendors/Textpattern/Skin/Skin.php
- textpattern/vendors/Textpattern/Skin/SkinBase.php
- textpattern/vendors/Textpattern/Skin/SkinInterface.php
- textpattern/vendors/Textpattern/Skin/Styles.php
- textpattern/vendors/Textpattern/Skin/gb.textpack
As discussed with @Bloke  and @philwareham by email, here is a pull request introducing an initial Skin package to manage related features. Basics work, advanced features and callbacks still need some tests. Happy debug!
- [Main](https://github.com/NicolasGraph/textpattern/blob/themes/textpattern/vendors/Textpattern/Skin/Main.php) manages multiple themes features;
- [Skin](https://github.com/NicolasGraph/textpattern/blob/themes/textpattern/vendors/Textpattern/Skin/Skin.php) manages a single theme and its assets (pages, forms and styles);
- [Pages](https://github.com/NicolasGraph/textpattern/blob/themes/textpattern/vendors/Textpattern/Skin/Pages.php) manages a defined skin related pages;
- [Forms](https://github.com/NicolasGraph/textpattern/blob/themes/textpattern/vendors/Textpattern/Skin/F …
> Adds Skin package (includes txp_skin.php changes)

- textpattern/include/txp_skin.php
fixed error:
```
User_Error "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 's WHERE s.skin = txp_skin.name) section_count,
(SELECT COUNT(*) FROM' at line 2"
```
wrong query:
```
SELECT *,
(SELECT COUNT(*) FROM x_txp_section as txp_section s WHERE s.skin = txp_skin.name) section_count,
(SELECT COUNT(*) FROM x_txp_page as txp_page p WHERE p.skin = txp_skin.name) page_count,
(SELECT COUNT(*) FROM x_txp_form as txp_form f WHERE f.skin = txp_skin.name) form_count,
(SELECT COUNT(*) FROM x_txp_css as txp_css c WHERE c.skin = txp_skin.name) css_count FROM x_txp_skin as txp_skin WHERE 1 order by name desc limit 0, 12
```
> Correct sql query

- textpattern/setup/index.php
- textpattern/setup/manifest.json
Added check of `txp-type`, so that instead of the theme it was impossible to install a plugin or anything else.
> Universal setup: Added check `txp-type`

- textpattern/vendors/Textpattern/Skin/Main.php
PHP 5.4.45
Error:
> Parse error: syntax error, unexpected '=', expecting ')' in /home/vhosts/repo_txp/txp_themes/textpattern/textpattern/vendors/Textpattern/Skin/Main.php on line 286
---
[php function empty()](http://php.net/manual/en/function.empty.php)
> Prior to PHP 5.5, **empty() only supports variables**; anything else will result in a parse error. In other words, the following will not work: empty(trim($name)). Instead, use trim($name) == false.
> Fix empty() syntax error

- textpattern/include/txp_skin.php
- textpattern/setup/data/txp_skin.xml
- textpattern/update/_to_4.7.0.php
- textpattern/vendors/Textpattern/DB/Tables/txp_skin.table
- textpattern/vendors/Textpattern/Skin/Main.php
- textpattern/vendors/Textpattern/Skin/Skin.php
See https://github.com/textpattern/textpattern/issues/950. 
- Table/JSON field `website`changed to `author_uri`;
- JSON field `name` renamed to `title` (it is what it contains; the theme name comes from its directory name).
> Skin table/JSON fields consistency

- HISTORY.txt
Some of the 4.7.0 release notes break the 80 character barrier, so I've trimmed.
Obviously ignore this PR if I missed a memo on an increase on the 80 character limit…
> Tweak `HISTORY.txt` wording, max 80 chars for uniformity.

- HISTORY.txt
- non-markup theme elements (images etc) are not stored in the database
- Cmd+S works for article Publish and Save, also
- clarified form recursion
- reworded a couple of `now accepts` instances for uniformity – it's clear from the bullet header there's a change, so `now` is unnecessary
- caps case on `Pages`, `Styles` and `Forms`
> Proof read `HISTORY.txt`

- HISTORY.txt
- update `HISTORY` to add info about ye olde Textpattern-e version jumps
Partially addresses https://github.com/textpattern/textpattern/issues/1257
> Add info about <4.2.0 jump

- textpattern/vendors/Textpattern/Skin/AssetBase.php
- textpattern/vendors/Textpattern/Skin/Skin.php
Hi, Comming back from holidays I see minimum requirements have changed; here is a Skin package related update to use the `JSON_PRETTY_PRINT` flag on `json_encode()` instead of a custom method. It could also be used in `TEXTPATTERN_JSON` directly but I don't think that it is useful for now.
> Skin php update

- textpattern/vendors/Textpattern/Skin/CommonBase.php
- Removes duplicated `AND` in queries to be usable by asset related classes (mostly for the future…).
- adds spaces where missing.
> Fixes potential duplicated AND in queries

- textpattern/vendors/Textpattern/Skin/AssetBase.php
- keep `setDir()` static but do not return `$this`;
- make `resetEditing()` an object related method to support `$this`.
Note that both methods are protected and not in use for now so they are not that useful…
> Fixes $this in static Skin related methods

- textpattern/include/txp_auth.php
See https://github.com/textpattern/textpattern/issues/1377 for background.
Adds a `txp-maskable` input class to current password field. Nothing else.
This should resolve the above issue, though there's a semantics question - should `Show password` be plural since there are two passwords on the panel?
Alternative route might be to have an additional `Show password` checkbox to toggle each input individually - any strong feelings on that @philwareham ?
> Add `txp-maskable` input class to current password

- textpattern/vendors/Textpattern/Skin/Css.php
- textpattern/vendors/Textpattern/Skin/Form.php
- textpattern/vendors/Textpattern/Skin/Page.php
first pass at https://github.com/textpattern/textpattern/issues/1766
- Tidy up
- Remove erroneous references
- Remove links to specific tags in favour of docs landing page
Requesting review from @Bloke or @bloatware since it's PHP territory and the array escaping might not be best practice.
> tidy up & fix empty theme commentary

- sites/site1/admin/plugins/.htaccess-dist
- textpattern/lib/constants.php
See Issue #1775 – on multisite installations, save plugins inside the multisite's admin directory.
- addition of `/plugins` directory inside `/sites/site1/admin/` with corresponding `.htaccess-dist`.
- Set PLUGINPATH constant to be `/sites/{sitename}/admin/plugin` if the site is a multisite installation, otherwise use the regular `textpattern/plugins`location.
> Multisite plugins directory inside site folder

- textpattern/include/txp_diag.php
Silence PHP 8.1 – Deprecated “passing null to version_compare()” notice on Diagnostics panel when no prerelease exists.
- only perform prerelease version comparison when $prerelease is set and not null.
Addresses issue #1786.
> Update txp_diag.php / Silence passing null notice

- textpattern/include/txp_tag.php
- textpattern/lib/txplib_html.php
- textpattern/publish/comment.php
- textpattern/publish/taghandlers.php
Appease the W3C validator…
txp_tag.php
- class BuilderTags (tag builder for html image code)
txplib_html.php
- function: tag_void (used in fInput)
- function: doWrap for br/hr break attributes
- function: doTag when content is empty
- function: doLabel break
comment.php
- function: input (for comments)
taghandlers.php
- function: txp:image
- function: txp:article_image
- function: txp:meta_keywords
- function: txp:meta_description
- function: txp:meta_author
- function: txp:feed_link / link_feed_link
- searchinput + popup
- rsd link
(this patch deviates only slightly from the corresponding patch for the main branch as function doWrap has changed slightly in the dev branch)
> Self-closing tag ending acc. to doctype setting

- textpattern/include/txp_prefs.php
Fixes #1873.
- Comment wording.
> Make trailing_slash() function comment relates to its behaviour.

- textpattern/publish/taghandlers.php
- format="" attribute for direct css output.
- format="inline" attribute for output in a <style> tag.
- support for escape attributes for inline output.
The "inline" option is self-explanatory. The empty option allows one to construct an own style tag, for example with a nonce, to construct a style block out of several stylesheets, or to output a stylesheet twice, as is common, for example, when providing dark mode variables for system-set dark mode (e.g. via @media) or user-set dark mode (e.g. via class or data-attribute).
The query is saved in a static variable should the same stylesheet be output more than once.
The underlying motivation is to allow stylesheet entries in _Presentation › Styles_ to be used as user-editable theme overrides …
> txp:css format attributes for inline output

- textpattern/lib/txplib_html.php
- textpattern/publish/taghandlers.php
- textpattern/vendors/Textpattern/Tag/Syntax/Comment.php
- textpattern/vendors/Textpattern/Tag/Syntax/File.php
- textpattern/vendors/Textpattern/Tag/Syntax/Image.php
The `br` constant remains unchanged. 
- Alter remaining public-side tag references to `br` as the default break attribute to `'br'` so they are not processed as the constant.
- Two label-input separators are made html5-compliant.
- Drop extra space when there are no $breakatts for br and hr tags.
> Pragmatic solution for remaining html5 compliant br break tags
